// <auto-generated />
namespace N01609602_ShreyPatel_PassionProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Collaborators : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Collaborators));
        
        string IMigrationMetadata.Id
        {
            get { return "202402010158148_Collaborators"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
